-- ============================================================
-- SCHEMA DEFINITION: Stock Portfolio Analysis & Tracking System
-- ============================================================

CREATE TABLE APP_USER (
    USER_ID VARCHAR2(10) PRIMARY KEY,
    FNAME VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30),
    LNAME VARCHAR2(30) NOT NULL,
    DOB DATE NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_STATUS VARCHAR2(15) DEFAULT 'ACTIVE'
);

CREATE TABLE INVESTOR (
    USER_ID VARCHAR2(10) PRIMARY KEY,
    RISK_PROFILE VARCHAR2(20),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE ADVISOR (
    ADVISOR_ID VARCHAR2(10) PRIMARY KEY,
    USER_ID VARCHAR2(10) NOT NULL,
    EXPERTISE VARCHAR2(100),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE ADMIN (
    ADMIN_ID VARCHAR2(10) PRIMARY KEY,
    USER_ID VARCHAR2(10) NOT NULL,
    PERMISSIONS VARCHAR2(500),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE CLIENT (
    CLIENT_ID VARCHAR2(10) PRIMARY KEY,
    CLIENT_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE INDIVIDUAL (
    IND_ID VARCHAR2(10) PRIMARY KEY,
    CLIENT_ID VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE
);

CREATE TABLE INSTITUTIONAL (
    INS_ID VARCHAR2(10) PRIMARY KEY,
    CLIENT_ID VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE
);

CREATE TABLE PORTFOLIO (
    PORTFOLIO_ID VARCHAR2(10) PRIMARY KEY,
    USER_ID VARCHAR2(10) NOT NULL,
    PORTFOLIO_NAME VARCHAR2(50) NOT NULL,
    CASH_BALANCE NUMBER(15,2) DEFAULT 0.00 NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE STOCK (
    STOCK_ID VARCHAR2(10) PRIMARY KEY,
    STOCK_SYMBOL VARCHAR2(20) NOT NULL UNIQUE,
    STOCK_NAME VARCHAR2(100) NOT NULL,
    EXCHANGE VARCHAR2(20) NOT NULL,
    SECTOR VARCHAR2(50),
    CURRENT_PRICE NUMBER(15,2) NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE STOCK_PRICE_HISTORY (
    PRICE_ID NUMBER PRIMARY KEY,
    STOCK_ID VARCHAR2(10) NOT NULL,
    PRICE_DATE DATE NOT NULL,
    OPENING_PRICE NUMBER(15,2),
    CLOSING_PRICE NUMBER(15,2) NOT NULL,
    HIGH_PRICE NUMBER(15,2),
    LOW_PRICE NUMBER(15,2),
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID) ON DELETE CASCADE
);

CREATE TABLE HOLDING (
    HOLDING_ID VARCHAR2(10) PRIMARY KEY,
    PORTFOLIO_ID VARCHAR2(10) NOT NULL,
    STOCK_ID VARCHAR2(10) NOT NULL,
    TOTAL_QUANTITY NUMBER(15,4) NOT NULL,
    AVG_PRICE NUMBER(15,2) NOT NULL,
    FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID) ON DELETE CASCADE,
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
    TRANS_ID VARCHAR2(10) PRIMARY KEY,
    PORTFOLIO_ID VARCHAR2(10) NOT NULL,
    STOCK_ID VARCHAR2(10) NOT NULL,
    QUANTITY NUMBER(15,4) NOT NULL,
    TRANS_FEE NUMBER(15,2) NOT NULL,
    TRANS_DATE DATE NOT NULL,
    FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID) ON DELETE CASCADE,
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID) ON DELETE CASCADE
);

CREATE TABLE BUY_TRANSACTION (
    BUY_ID VARCHAR2(10) PRIMARY KEY,
    TRANS_ID VARCHAR2(10) NOT NULL,
    BUY_BROKERAGE NUMBER(15,2) NOT NULL,
    FOREIGN KEY (TRANS_ID) REFERENCES TRANSACTIONS(TRANS_ID) ON DELETE CASCADE
);

CREATE TABLE SELL_TRANSACTION (
    SELL_ID VARCHAR2(10) PRIMARY KEY,
    TRANS_ID VARCHAR2(10) NOT NULL,
    SELL_BROKERAGE NUMBER(15,2) NOT NULL,
    FOREIGN KEY (TRANS_ID) REFERENCES TRANSACTIONS(TRANS_ID) ON DELETE CASCADE
);

CREATE TABLE WATCHLIST_ITEM (
    USER_ID VARCHAR2(10) NOT NULL,
    WATCH_ID VARCHAR2(10) NOT NULL,
    ADDED_AT DATE NOT NULL,
    PRIMARY KEY (USER_ID, WATCH_ID),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE WATCHLIST_STOCK (
    USER_ID VARCHAR2(10) NOT NULL,
    WATCH_ID VARCHAR2(10) NOT NULL,
    STOCK_ID VARCHAR2(10) NOT NULL,
    REFERENCE_NO VARCHAR2(30),
    PRIMARY KEY (USER_ID, WATCH_ID, STOCK_ID),
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID) ON DELETE CASCADE
);

CREATE TABLE ADVISOR_WATCHLIST (
    ADVISOR_ID VARCHAR2(10) NOT NULL,
    USER_ID VARCHAR2(10) NOT NULL,
    WATCH_ID VARCHAR2(10) NOT NULL,
    TRACKED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ADVISOR_ID, USER_ID, WATCH_ID),
    FOREIGN KEY (ADVISOR_ID) REFERENCES ADVISOR(ADVISOR_ID) ON DELETE CASCADE
);